excluded:
  - ".build"
  - "**/.build"
  - "**/Pods"
  - "**/generated"

disabled_rules:
  - function_parameter_count
  - identifier_name
  - todo
  - force_cast
  - force_try
  - file_length
  - type_body_length
  - empty_enum_arguments
  - type_name
  - line_length
  - opening_brace
  - trailing_comma
  - vertical_whitespace
  - vertical_parameter_alignment
  - comment_spacing
  - trailing_newline
  - trailing_whitespace
  - function_body_length
  - comma

opt_in_rules:
  - anyobject_protocol
  - array_init
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - ibinspectable_in_extension
  - identical_operands
  - implicitly_unwrapped_optional
  - last_where
  - nslocalizedstring_key
  - override_in_extension
  - overridden_super_call
  - prefer_zero_over_explicit_init
  - private_action
  - prohibited_super_call
  - quick_discouraged_focused_test
  - reduce_into
  - sorted_first_last
  - strong_iboutlet
  - unowned_variable_capture

analyzer_rules:
  - unused_import
  - unused_declaration
  - explicit_self

# Rules Configuration

indentation: 2

colon:
  flexible_right_spacing: true

cyclomatic_complexity:
  ignores_case_statements: true

large_tuple:
  warning: 5

nesting:
  type_level: 3

custom_rules:
  print_expression:
    name: "Unexpected print expression"
    message: "print should not be used for logging."
    regex: 'print\(".+?"\)'
    severity: warning

  l10n_comment_raw_string:
    name: "Raw string used for NSLocalizedString comment"
    message: "Raw strings should not be used for NSLocalizedString comments because they are not exported correctly. Use a normal String literal."
    regex: 'comment: ?#".*?"#'
    severity: warning

  l10n_comment_empty:
    name: "Empty comment in NSLocalizedString"
    message: "NSLocalizedString should include a comment to provide translation context."
    regex: 'comment: ?#?"\s*"#?'
    severity: warning
